// <auto-generated />
namespace MyFirstApp1399.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class createee : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createee));
        
        string IMigrationMetadata.Id
        {
            get { return "202005292001374_createee"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
